from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class AgentRunRequest(BaseModel):
    input_value: str = Field(..., description="Message input to the AI agent")

class AgentRunResponse(BaseModel):
    response: str = Field(..., description="Response generated by the agent")
    intent: str = Field(..., description="Detected intent of the input")
    confidence: float = Field(..., description="Confidence score of the intent classification (0.0 to 1.0)")
    tokens_used: int = Field(..., description="Total tokens consumed during processing")
    latency_ms: int = Field(..., description="Processing latency in milliseconds")

class ValidationRules(BaseModel):
    must_contain: List[str] = Field(default_factory=list, description="Keywords that must be present in the response")
    forbidden: List[str] = Field(default_factory=list, description="Keywords that must NOT be present in the response")

class TestCase(BaseModel):
    id: str = Field(..., description="Unique test case identifier")
    input: str = Field(..., description="Citizen input string")
    expected_intent: str = Field(..., description="Expected intent classification")
    validation_rules: ValidationRules = Field(..., description="Rules to validate response text conformity")
    category: str = Field(..., description="Test category (e.g. réclamation, demande administrative, question sensible, erreur volontaire)")

class TestRunResult(BaseModel):
    test_id: str
    category: str
    input: str
    expected_intent: str
    detected_intent: str
    agent_response: str
    conformity_score: float
    intent_matched: bool
    success: bool
    details: List[str]

class GlobalReportResponse(BaseModel):
    timestamp: str
    total_tests: int
    passed_tests: int
    failed_tests: int
    global_score: float
    success_rate: float
    results: List[TestRunResult]

class WorkflowExport(BaseModel):
    workflow_name: str
    version: str
    agents: List[Dict[str, Any]]
    test_cases: List[TestCase]
    validation_rules_summary: Dict[str, Any]
